name: buildmacOS

# on: [push, pull_request]
on: 
  workflow_dispatch:

env:
  REPO_URL: https://github.com/laurent22/joplin
  REPO_BRANCH: dev

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Set npm config flags
      run: |
        corepack enable
        export npm_config_arch=arm64
        export npm_target_arch=arm64
        export sdkroot=macosx
        npm config set python python3
        
    - name: Clone source code      
      run: |        
        git clone $REPO_URL -b $REPO_BRANCH joplin   
        
    - name: modify the traget
      run: |
        sed -i '' 's/\"target\": \"dmg\",/\"target\": \{\"target\": \"default\",\"arch\": \[\"x64\",\"arm64\", \"universal\"]},/g' joplin/packages/app-desktop/package.json
        
    - name: Initializate environment
      run: |      
        brew install vips
        node --version

    - name: Build & pack
      run: |
        # cd joplin
        # yarn install
        # cd packages/app-desktop
        # yarn run dist --publish=never --mac --arm64
        # yarn run dist
        
    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        # GitHub token, automatically provided to the action
        # (No need to define this secret in the repo settings)
        github_token: ${{ secrets.github_token }}    
        package_root: joplin/packages/app-desktop

        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      

    - name: Upload firmware directory
      uses: actions/upload-artifact@main      
      with:
        path:
          "**/*.dmg"
    
