name: buildmacOS

on: [push, pull_request]

env:
  REPO_URL: https://github.com/laurent22/joplin
  REPO_BRANCH: dev


jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    
    
              
    - name: Install npm packages
      run: |
        # npm install sharp
        # For some reason npm will throw errors if keytar not built beforehand
        # npm install Keytar —build-from-source 
        # npm install -g @dennisameling/keytar-temp@7.4.99 ## Alt keytar if above does not work
        # npm install sqlite3@4.1.0 —build-from-source ## Might not be necessary, run if build fails in step 3
        
    - name: Set npm config flags
      run: |
        corepack enable
        export npm_config_arch=arm64
        export npm_target_arch=arm64
        export sdkroot=macosx
        npm config set python python3
        
    - name: Clone source code      
      run: |        
        git clone $REPO_URL -b $REPO_BRANCH joplin
        # ln -sf /workdir/openwrt $GITHUB_WORKSPACE/joplin        
    
        
    - name: modify the traget
      run: |
      sed -i '' 's/\"target\": \"dmg\",/\"target\": \{\"target\": \"default\",\"arch\": \[\"x64\",\"arm64\"]},/g' joplin/packages/app-desktop/package.json
        
    - name: Initialization environment
      run: |      
        brew install vips

    - name: Install npm packages
      run: |
        cd joplin
        yarn install
        cd packages/app-desktop      
        # if it runs successfully, time to package
        yarn run dist --publish=never --mac --arm64

    - name: Upload firmware directory
      uses: actions/upload-artifact@main      
      with:
        path: |
          'packages/app-desktop/dist/Joplin-*-arm64.dmg'
          'packages/app-desktop/dist/Joplin-*-mac.dmg'
    
