name: Check for updates

on:
  schedule:
 
    - cron:  '* */5 * * *'
  workflow_dispatch:

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - run: |
        RELEASE_VER=$(git -c 'versionsort.suffix=-' \
            ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/laurent22/joplin.git 'v*.*.*' \
            | tail --lines=1 \
            | cut --delimiter='/' --fields=3)

        LOCAL_VER=$(git -c 'versionsort.suffix=-' \
            ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/n1majne3/Joplin-Action-for-macOS.git \
            | tail --lines=1 \
            | cut --delimiter='/' --fields=3)

        if [[ $RELEASE_VER != $LOCAL_VER ]]; then
            echo "Local version: $LOCAL_VER"
            echo "Latest upstream version: $RELEASE_VER"
            echo "Updating to latest version..."
            git tag ${RELEASE_VER}
            git push origin ${RELEASE_VER}
        else
            echo "No updates available..."
        fi
