name: test

# on: [push, pull_request]
on: 
  workflow_dispatch:

env:
  REPO_URL: https://github.com/laurent22/joplin
  REPO_BRANCH: dev

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Set npm config flags
      run: |
        corepack enable
        export npm_config_arch=arm64
        export npm_target_arch=arm64
        export sdkroot=macosx
        npm config set python python3
        
    - name: Clone source code      
      run: |        
        git clone $REPO_URL -b $REPO_BRANCH joplin   
        
    - name: modify the traget
      run: |
        sed -i '' 's/\"target\": \"dmg\",/\"target\": \{\"target\": \"default\",\"arch\": \[\"x64\",\"arm64\", \"universal\"]},/g' joplin/packages/app-desktop/package.json
        
    - name: Initializate environment
      run: |      
        brew install vips
        node --version

    - name: Build & pack
      run: |
        cd joplin
        
        yarn install
        tag=cat package.json|grep \"version\"|awk  '{print $2}'|sed 's/"//g'
        echo "TAG=v$tag" >> $GITHUB_ENV
        echo $tag
        env
        cd packages/app-desktop
        # yarn run dist --publish=never --mac --arm64
        yarn run dist --publish=never
        echo "DIST=$PWD/dist" >> $GITHUB_ENV
              
        
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG }}     
        files: ${{ env.DIST }}/*
    
      

    - name: Upload firmware directory
      uses: actions/upload-artifact@main      
      with:
        path:
          #"**/*.dmg"
          ${{ env.DIST }}/*.dmg
    
